awsomecv/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
app_name='resume'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume.urls', namespace='resume')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.urls import path
from . import views
app_name = 'resume'
urlpatterns = [
    #path('',views.my_profile,name='my_profile'),
    path('',views.index, name='about'),
    path('experience',views.experience, name='experience'),
    path('portfolio',views.portfolio, name='portfolio'),
    path('skills',views.skills, name='skills'),
    path('awards',views.awards, name='awards'),
    path('contact',views.emailView, name='contact'),

]

resume/models.py
from django.db import models

# Create your models here.

resume/forms.py
from django import forms

class ContactForm(forms.Form):
    your_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

resume/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm

# Create your views here.

def index(request):
    return render(request, 'about.html')

def experience(request):
    return render(request, 'experience.html')

def portfolio(request):
    return render(request, 'portfolio.html')

def skills(request):
    return render(request, 'skills.html')

def awards(request):
    return render(request, 'awards.html')

#def contact(request):
#    return render(request, 'contact.html')

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            your_email = form.cleaned_data['your_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, your_email, ['nabirhossain13@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return render(request, 'success.html')
    return render(request, 'contact.html', {'form': form})

resume/templates/about.html
{% extends 'index.html' %}
{% load static %}


{% block content %}
<!--====================================================
                        ABOUT
    ======================================================-->
      <section class="resume-section p-3 p-lg-5 d-flex d-column" id="about">
          <div class="my-auto" >
              <img src="{% static 'img/logo-s.png' %}" class="img-fluid mb-3" alt="">
              <h1 class="mb-0">Mohammad
                <span class="text-primary">NABIR HOSSAIN</span>
              </h1>
              <div class="subheading mb-5">THE NEXT BIG IDEA IS WAITING FOR ITS NEXT BIG CHANGER WITH
                  <a href="#">THEMSBIT</a>
              </div>
              <p class="mb-5" style="max-width: 500px;" >I am experienced in leveraging agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition.</p>
              <ul class="list-inline list-social-icons mb-0">
                  <li class="list-inline-item">
                      <a href="https://www.facebook.com/profile.php?id=100008592640528">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
                  </li>
                  <li class="list-inline-item">
                      <a href="https://twitter.com/MdNabirHossain3">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
                  </li>
                  <li class="list-inline-item">
                      <a href="https://www.linkedin.com/in/nabir-hossain-a72249106/">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
                  </li>
                  <li class="list-inline-item">
                      <a href="https://github.com/nabirhossain">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
                  </li>
              </ul>
          </div>
      </section>

{% endblock %}

resume/templates/awards.html
{% extends 'index.html' %}
{% load static %}


{% block content %}

    <!--====================================================
                           AWARDS
    ======================================================-->
      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="awards">
          <div class="row my-auto">
              <div class="col-12">
                <h2 class="  text-center">Awards</h2>
                <div class="mb-5 heading-border"></div>
              </div>
              <div class="main-award" id="award-box">
                  <div class="award">
                      <div class="award-icon"></div>
                      <div class="award-content">
                          <span class="date">Apr 2017 - Mar 2018</span>
                          <h5 class="title">Google Analytics Certified Developer</h5>
                          <p class="description">
                              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum mattis felis vitae risus pulvinar tincidunt. Nam ac venenatis enim. Aenean hendrerit justo sed.
                          </p>
                      </div>
                  </div>
                  <div class="award">
                      <div class="award-icon"></div>
                      <div class="award-content">
                          <span class="date">Apr 2018 - Mar 2019</span>
                          <h5 class="title">Mobile Web Specialist - Google Certification</h5>
                          <p class="description">
                              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum mattis felis vitae risus pulvinar tincidunt. Nam ac venenatis enim. Aenean hendrerit justo sed.
                          </p>
                      </div>
                  </div>
              </div>
          </div>
      </section>
{% endblock %}

resume/templates/contact.html
{% extends 'index.html' %}
{% load static %}


{% block content %}
<!--====================================================
                          CONTACT
    ======================================================-->
      <section class="resume-section p-3 p-lg-5 d-flex flex-column">
          <div class="row my-auto" id="contact">
            <div class="col-md-8">
              <div class="contact-cont">
                <h3>CONTACT Me</h3>
                <div class="heading-border-light"></div>
                <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here.</p>
              </div>
              <form method="post" role="form">{% csrf_token %}
                <div class="row con-form">
                  <div class="col-md-12">
                    <input type="text" name="your_email" placeholder="Your Email" class="form-control">
                  </div>
                  <div class="col-md-12">
                    <input type="text" name="subject" placeholder="Email Subject" class="form-control">
                  </div>
                  <div class="col-md-12"><textarea name="message" id="" placeholder="write your message here..." class="form-control"></textarea></div>
                  <div class="col-md-12 sub-but"><button class="btn btn-general btn-white" role="button">Send</button></div>
                </div>
              </form>

          </div>
            <div class="col-md-4 col-sm-12 mt-5">
              <div class="contact-cont2">
                <div class="contact-add contact-box-desc">
                  <h3><i class="fa fa-map-marker cl-atlantis fa-2x"></i> Address</h3>
                  <p>Fatulah, Naraynagonj <br>
                  Bangladesh<br></p>
                </div>
                <div class="contact-phone contact-side-desc contact-box-desc">
                  <h3><i class="fa fa-phone cl-atlantis fa-2x"></i> Phone</h3>
                  <p>+8801719337456<br>+8801625265685</p>
                </div>
                <div class="contact-mail contact-side-desc contact-box-desc">
                  <h3><i class="fa fa-envelope-o cl-atlantis fa-2x"></i> Email</h3>
                <address class="address-details-f">
                  Email: <a href="mailto:nabirhossain13@gmail.com" class="">nabirhossain13@gmail.com</a>
                </address>
                <ul class="list-inline social-icon-f top-data">
                  <li><a href="https://www.facebook.com/profile.php?id=100008592640528" target="_empty"><i class="fa top-social fa-facebook" style="color: #4267b2; border-color:#4267b2;"></i></a></li>
                  <li><a href="https://twitter.com/MdNabirHossain3" target="_empty"><i class="fa top-social fa-twitter" style="color: #4AB3F4; border-color:#4AB3F4;"></i></a></li>
                  <li><a href="https://plus.google.com/u/0/116561509278696653736?tab=qX" target="_empty"><i class="fa top-social fa-google-plus" style="color: #e24343; border-color:#e24343;"></i></a></li>
                </ul>
                </div>
              </div>
            </div>
          </div>
      </section>

      <section class=" d-flex flex-column" id="maps">
        <div id="map">
          <div class="map-responsive">
              <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d58469.378452778365!2d90.46643827885404!3d23.66393378130325!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbd!4v1533618815803" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

          </div>
        </div>
      </section>
{% endblock %}








<!--
                    <div class="col-md-12">
                      <input type="text" name="your_name" placeholder="Full Name" class="form-control">
                    </div>
                    <div class="col-md-12">
                      <input type="email" name="your_email" placeholder="Email Id" class="form-control">
                    </div>
                    <div class="col-md-12">
                      <input type="text" name="subject" placeholder="Subject" class="form-control">
                    </div>
                    <div class="col-md-12"><textarea name="message" id=""></textarea></div>
                    <div class="col-md-12 sub-but">
                        <button class="btn btn-general btn-white" role="button" type="submit">Send</button>
                    </div>
-->

resume/templates/experience.html
{% extends 'index.html' %}
{% load static %}


{% block content %}

<!--====================================================
                        EXPERIENCE
    ======================================================-->
      <section class="resume-section p-3 p-lg-5 " id="experience">
          <div class="row my-auto">
              <div class="col-12">
                <h2 class="  text-center">Experience</h2>
                <div class="mb-5 heading-border"></div>
              </div>
              <div class="resume-item col-md-6 col-sm-12 " >
                <div class="card mx-0 p-4 mb-5" style="border-color: #17a2b8; box-shadow: 2px 2px 2px rgba(0, 0, 0, 0.21);">
                  <div class=" resume-content mr-auto">
                      <h4 class="mb-3"><i class="fa fa-globe mr-3 text-info"></i> Senior Web Developer</h4>
                      <p>Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.</p>
                  </div>
                  <div class="resume-date text-md-right">
                      <span class="text-primary">March 2019 - Present</span>
                  </div>
                </div>
              </div>
              <div class="resume-item col-md-6 col-sm-12">
                <div class="card mx-0 p-4 mb-5" style="border-color: #ffc107; box-shadow: 2px 2px 2px rgba(0, 0, 0, 0.21);">
                  <div class="resume-content mr-auto">
                      <h4 class="mb-3"><i class="fa fa-laptop mr-3 text-warning"></i>  Web Developer</h4>
                      <p>Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.</p>
                  </div>
                  <div class="resume-date text-md-right">
                      <span class="text-primary">December 2018 - March 2019</span>
                  </div>
                </div>
              </div>
              <div class="resume-item col-md-6 col-sm-12">
                <div class="card mx-0 p-4 mb-5" style="border-color: #28a745; box-shadow: 2px 2px 2px rgba(0, 0, 0, 0.21);">
                  <div class="resume-content mr-auto">
                      <h4 class="mb-3"><i class="fa fa-camera mr-3 text-success"></i> Junior Web Designer</h4>
                      <p>Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.</p>
                  </div>
                  <div class="resume-date text-md-right">
                      <span class="text-primary">July 2017 - December 2018</span>
                  </div>
                </div>
              </div>
              <div class="resume-item col-md-6 col-sm-12">
                <div class="card mx-0 p-4 mb-5" style="border-color: #2196f3; box-shadow: 2px 2px 2px rgba(0, 0, 0, 0.21);">
                  <div class="resume-content mr-auto">
                      <h4 class="mb-3"><i class="fa fa-area-chart mr-3 text-primary"></i> Web Design Intern</h4>
                      <p>Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.</p>
                  </div>
                  <div class="resume-date text-md-right">
                      <span class="text-primary">September 2018 - June 2019</span>
                  </div>
                </div>
              </div>
          </div>
      </section>
{% endblock %}

resume/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <title>My Profile</title>
    {% block stylesheet %}
    <!-- Global stylesheets -->
    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/devicons/css/devicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <style type="text/css">
        #about {
      background-image: url("{% static 'img/profile-banner.jpg' %}");
      background-size: cover;
      background-position: center center;
      background-repeat: no-repeat;
  }

  #about h1 {
    /*font-size: 100%;*/
  }
  #about p{
    color: white;
  }
    #skills {
    background-image: url({% static 'img/bg-stats.jpg' %});
    background-size: cover;
    background-position: center center;
    background-repeat: no-repeat;
}

    </style>
    {% endblock %}
</head>

<body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <span class="d-block d-lg-none  mx-0 px-0"><img src="{% static 'img/logo-white.png' %}" alt="" class="img-fluid"></span>
        <span class="d-none d-lg-block">
          <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'img/621547647f3b4d.jpg' %}" alt="">
        </span>
      </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'resume:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'resume:experience' %}">Experience</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'resume:portfolio' %}">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'resume:skills' %}">Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'resume:awards' %}">Awards</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'resume:contact' %}">Contact</a>
                </li>
            </ul>
        </div>
    </nav>
       {% block content %}
    <div class="container-fluid p-0">



    </div>
       {% endblock %}
</body>

</html>
{% block script %}

    <!-- Global javascript -->
    <script src="{% static 'js/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/counter/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/counter/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function(){
        $(".filter-b").click(function(){
            var value = $(this).attr('data-filter');
            if(value == "all")
            {
                $('.filter').show('1000');
            }
            else
            {
                $(".filter").not('.'+value).hide('3000');
                $('.filter').filter('.'+value).show('3000');
            }
        });

        if ($(".filter-b").removeClass("active")) {
          $(this).removeClass("active");
        }
        $(this).addClass("active");
        });

        // SKILLS
        $(function () {
            $('.counter').counterUp({
                delay: 10,
                time: 2000
            });

        });
    </script>

{% endblock %}

resume/templates/skills.html
 {% extends 'index.html' %}
 {% load static %}


{% block content %}
    <!--====================================================
                        SKILLS
    ======================================================-->
      <section class=" d-flex flex-column" id="skills">
         <div class="p-lg-5 p-3 skill-cover">
          <h3 class="text-center text-white">Coding Skills</h3>
          <div class="row text-center my-auto ">
              <div class="col-md-3 col-sm-6">
                  <div class="skill-item">
                      <i class="fa fa-html5 fa-5x"></i>
                      <h2><span class="counter"> 84 </span><span>%</span></h2>
                      <p>HTML5</p>
                  </div>
              </div>
              <div class="col-md-3 col-sm-6">
                  <div class="skill-item">
                      <i class="fa fa-css3 fa-5x"></i>
                      <h2><span class="counter"> 95 </span><span>%</span></h2>
                      <p>CSS3</p>
                  </div>
              </div>
              <div class="col-md-3 col-sm-6">
                  <div class="skill-item">
                      <i class="fa fa-code fa-5x"></i>
                      <h2><span class="counter"> 65 </span><span>%</span></h2>
                      <p>JQuery</p>
                  </div>
              </div>
              <div class="col-md-3 col-sm-6">
                  <div class="skill-item">
                      <i class="fa fa-globe fa-5x"></i>
                      <h2><span class="counter"> 89 </span><span>%</span></h2>
                      <p>PHP</p>
                  </div>
              </div>
          </div>
         </div>
      </section>
{% endblock %}

resume/templates/success.html
{% extends 'index.html' %}



{% block content %}
<div class="container" style="margin-top: 80px;">
<h1>Submitted your message successfully. Thank you.</h1>
<a href="/"> <button class="btn btn-info">back</button></a>
</div>
{% endblock %}